import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./globals.css";

/*
1. While layouts are optional, the Root Layout is not because it contains the HTML boilerplate
(head tag is generated by Next.js automatically)

2. If we want content on every single page, put in Root Layout here!
*/

const inter = Inter({ subsets: ["latin"] });
// import { Montserrat } from "next/font/google";
// const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "bycherrie blog",
  description: "stay updated on bycherrie's muse and upcoming releases!",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
